const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const {DatabaseSync}=require('node:sqlite');const {SqlitePrintQueue}=require('../server/kiosk/print-v2-sqlite');
function setup(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE tickets(id TEXT PRIMARY KEY);
CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);
CREATE TABLE print_kiosks(id TEXT PRIMARY KEY,active INTEGER DEFAULT 1);
CREATE TABLE print_jobs(id TEXT PRIMARY KEY,ticket_id TEXT NOT NULL UNIQUE,kiosk_id TEXT,idempotency_key TEXT,status TEXT DEFAULT 'pending',payload TEXT,attempts INTEGER DEFAULT 0,claimed_at TEXT,printed_at TEXT,failed_at TEXT,last_error TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE print_job_attempts(id TEXT PRIMARY KEY,job_id TEXT,kiosk_id TEXT,attempt_number INTEGER,started_at TEXT,finished_at TEXT,duration_ms INTEGER,status TEXT,error_message TEXT,created_at TEXT);`);
 const queue=new SqlitePrintQueue(db),p=crypto.randomUUID(),d=crypto.randomUUID(),d2=crypto.randomUUID(),k='test';
 db.prepare("INSERT INTO print_printers(id,store_code,hardware_key,name) VALUES(?,'loja-2','TEST','Test')").run(p);
 db.prepare("INSERT INTO print_kiosks(id,printer_id,protocol_version,store_code) VALUES(?,?,2,'loja-2')").run(k,p);
 for(const id of [d,d2])db.prepare("INSERT INTO print_devices(id,kiosk_id,printer_id,store_code,name,token_hash,created_at) VALUES(?,?,?,'loja-2','Device',?,?)").run(id,k,p,id,new Date().toISOString());
 const call=(name,args={})=>{const result=queue.rpc(name,{p_device_id:d,...args});if(result?.error)throw new Error(result.error);return result};
 const claim=id=>call('claim_next_print_job_v2',{p_device_id:id||d,p_request_id:crypto.randomUUID()});
 const own=j=>({p_job_id:j.id,p_lease_id:j.lease_id,p_attempt_version:j.attempt_version});
 const job=()=>{const id=crypto.randomUUID();db.prepare("INSERT INTO print_jobs(id,kiosk_id,idempotency_key,payload,created_at,updated_at) VALUES(?,?,?,'{}',?,?)").run(id,k,id,new Date().toISOString(),new Date().toISOString());return id;};return {db,queue,d,d2,call,claim,own,job};}
test('SQLite mirrors printer exclusion, fencing and durable finish contract',()=>{const f=setup();try{f.job();f.job();const j=f.claim().job;assert.equal(f.claim(f.d2).job,null);assert.equal(f.claim().job,null);assert.throws(()=>f.call('start_print_job_v2',{...f.own(j),p_device_id:f.d2}),/owner/);f.call('start_print_job_v2',f.own(j));const a={...f.own(j),p_outcome:'printed'};const accepted=f.call('finish_print_job_v2',a);assert.deepEqual(f.call('finish_print_job_v2',a),accepted);assert.ok(f.claim(f.d2).job)}finally{f.db.close()}});
test('SQLite expired printing remains visible and blocks a second writer',()=>{const f=setup();try{f.job();const j=f.claim().job;f.call('start_print_job_v2',f.own(j));f.db.prepare("UPDATE print_jobs SET lease_expires_at='2000-01-01' WHERE id=?").run(j.id);assert.equal(f.call('recover_print_execution_v2').job.status,'needs_review');f.job();assert.equal(f.claim(f.d2).job,null);f.call('finish_print_job_v2',{...f.own(j),p_outcome:'printed'});assert.ok(f.claim(f.d2).job)}finally{f.db.close()}});
test('SQLite fifth unstarted attempt becomes terminal; old lease cannot finish a replacement',()=>{const f=setup();try{const id=f.job();const old=f.claim().job;f.db.prepare("UPDATE print_jobs SET lease_expires_at='2000' WHERE id=?").run(id);const newer=f.claim(f.d2).job;assert.notEqual(newer.lease_id,old.lease_id);assert.throws(()=>f.call('finish_print_job_v2',{...f.own(old),p_outcome:'printed'}),/owner/)}finally{f.db.close()}});
test('printed result wins over a stale local finish phase without reprinting',()=>{const f=setup();try{f.job();const j=f.claim().job;f.call('start_print_job_v2',f.own(j));const printed=f.call('finish_print_job_v2',{...f.own(j),p_outcome:'printed'});const replay=f.call('finish_print_job_v2',{...f.own(j),p_outcome:'unknown'});assert.deepEqual(replay,printed);assert.equal(f.db.prepare('SELECT status FROM print_jobs WHERE id=?').get(j.id).status,'printed')}finally{f.db.close()}});
