const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');
const {DurableStore}=require('../scripts/print-agent/durable-store');const {PrintConsumer}=require('../scripts/print-agent/consumer');
function fixture(count=1){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'print-v2-'));const store=new DurableStore(dir);let now=Date.now(),timer;const jobs=Array.from({length:count},()=>({id:crypto.randomUUID(),lease_id:crypto.randomUUID(),attempt_version:1,status:'leased',payload:{ticketCode:'T001',sectorName:'Teste',issuedAt:new Date().toISOString()}}));const calls=[];let sent=0,available=jobs.slice(),current=null;
 const api=async(command,body)=>{calls.push({command,body});if(command==='recover')return {job:current};if(command==='claim'){current=available.shift()||null;return {job:current}}if(command==='start'){current={...current,status:'printing',lease_expires_at:new Date(now+90000).toISOString()};return {job:current}}if(command==='finish'){current=null;return {job:{status:body.outcome==='unknown'?'needs_review':body.outcome==='printed'?'printed':'retry_wait'}}}};
 const printer={print:async()=>{sent++}};
 const consumer=new PrintConsumer({api,store,printer,clock:()=>now,setTimer:(fn,ms)=>(timer={fn,ms}),clearTimer:()=>{},random:()=>0.5});
 return {store,consumer,calls,jobs,printer,get sent(){return sent},get timer(){return timer},advance:(ms)=>{now+=ms},add:()=>available.push(...jobs),close:async()=>{await consumer.stop();store.close();fs.rmSync(dir,{recursive:true,force:true})}};
}
test('idle day uses only 144 safety reconciliations; no two-second claim loop',async()=>{const f=fixture(0);try{await f.consumer.wake();assert.equal(f.timer.ms,600000);for(let i=0;i<144;i++){f.advance(600000);await f.timer.fn()}assert.equal(f.calls.filter(c=>c.command==='claim').length,145)}finally{await f.close()}});
test('offline backlog drains one job at a time after subscription wake',async()=>{const f=fixture(10);try{assert.equal(f.calls.length,0);await f.consumer.wake();assert.equal(f.sent,10);assert.equal(f.store.pending().length,0)}finally{await f.close()}});
test('duplicate events coalesce and event during drain is not lost',async()=>{const f=fixture(1);try{f.printer.print=async()=>{for(let i=0;i<50;i++)f.consumer.wake()};await f.consumer.wake();assert.equal(f.calls.filter(c=>c.command==='start').length,1);assert.ok(f.calls.filter(c=>c.command==='claim').length<=3)}finally{await f.close()}});
test('lost Broadcast with connected socket is recovered by watchdog',async()=>{const f=fixture(0);try{await f.consumer.wake();f.jobs.push({id:crypto.randomUUID(),lease_id:crypto.randomUUID(),attempt_version:1,status:'leased',payload:{ticketCode:'T',sectorName:'T',issuedAt:new Date().toISOString()}});f.add();f.advance(600000);await f.timer.fn();assert.equal(f.sent,1)}finally{await f.close()}});
test('HTTP finish failure retains success and retries only finish',async()=>{const f=fixture(1);const api=f.consumer.api;let fail=true;f.consumer.api=async(c,b)=>{if(c==='finish'&&fail)throw new Error('offline');return api(c,b)};try{await f.consumer.wake();assert.equal(f.sent,1);assert.equal(f.store.pending()[0].outcome,'printed');fail=false;await f.consumer.wake();assert.equal(f.sent,1);assert.equal(f.store.pending().length,0)}finally{await f.close()}});
for(const phase of ['leased','starting','writing'])test('power loss at '+phase+' never blindly reprints',async()=>{const f=fixture(0);const job={id:crypto.randomUUID(),lease_id:crypto.randomUUID(),attempt_version:1};try{f.store.save(job,phase);await f.consumer.wake();assert.equal(f.sent,0);assert.equal(f.calls.find(c=>c.command==='finish').body.outcome,phase==='leased'?'before_send':'unknown')}finally{await f.close()}});
test('unknown physical outcome blocks and is persisted',async()=>{const f=fixture(1);try{f.printer.print=async()=>{throw new Error('partial write')};await f.consumer.wake();assert.equal(f.calls.find(c=>c.command==='finish').body.outcome,'unknown');assert.equal(f.consumer.state,'needs_review')}finally{await f.close()}});
test('printer offline before bytes is a recoverable failure',async()=>{const f=fixture(1);try{f.printer.print=async()=>{throw Object.assign(new Error('no paper'),{beforeSend:true})};await f.consumer.wake();assert.equal(f.calls.find(c=>c.command==='finish').body.outcome,'before_send')}finally{await f.close()}});
test('revocation leaves durable acknowledgements intact',async()=>{const f=fixture(0);try{const job={id:crypto.randomUUID(),lease_id:crypto.randomUUID(),attempt_version:1};f.store.save(job,'result','printed');f.consumer.api=async()=>{throw Object.assign(new Error('revoked'),{status:403})};await f.consumer.wake();assert.equal(f.store.pending().length,1);assert.equal(f.consumer.state,'unauthorized');assert.equal(f.sent,0)}finally{await f.close()}});
test('5000 receipts are drained without leasing ahead or retaining pending confirmations',async()=>{const f=fixture(5000);try{await f.consumer.wake();assert.equal(f.sent,5000);assert.equal(f.store.pending().length,0)}finally{await f.close()}});

test('OS lock rejects a second process-equivalent instance and releases cleanly',async()=>{
 const {acquirePrinterLock}=require('../scripts/print-agent/durable-store');
 const port='TEST-'+crypto.randomUUID();const release=await acquirePrinterLock(port);
 try{await assert.rejects(acquirePrinterLock(port),/Outra instancia/);}finally{await release();}
 const released=await acquirePrinterLock(port);await released();
});
