import Script from "next/script";

// The page shell contains Next's inline bootstrap scripts. Keep the shell
// request-rendered so the nonce generated by the proxy can be attached to
// those scripts instead of serving a prerendered HTML copy without it.
export const dynamic = "force-dynamic";

export const metadata = {
  title: {
    default: "SenhaHub - Supermercado Pompeia",
    template: "%s | SenhaHub"
  },
  applicationName: "SenhaHub",
  description: "Fila virtual e acompanhamento de atendimento do Supermercado Pompeia.",
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/senhahub-192.png", sizes: "192x192", type: "image/png" }
    ],
    apple: [
      { url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }
    ]
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "SenhaHub"
  },
  formatDetection: {
    telephone: false
  },
  other: {
    "mobile-web-app-capable": "yes"
  }
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#FF7200",
  colorScheme: "light"
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="/styles.css?v=20260921.7" />
        <link rel="stylesheet" href="/pwa.css?v=20260914.10" />
      </head>
      <body>
        {children}
        <Script src="/pwa-utils.js?v=20260904.4" strategy="afterInteractive" />
        <Script src="/pwa.js?v=20260905.3" strategy="afterInteractive" />
      </body>
    </html>
  );
}
